### PR TITLE
Allow the use of yocto_api as a Python package

### PR DESCRIPTION
**Pull request by LudovicRousseau**
The idea is to install the wrapper with a minimal impact in the site-packages directory.

I also provide a Python script to install the files.

Once the wrapper is installed it can be used with a simple line:
```
from yocto_api.yocto_colorled import *
```

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
Another idea after this change is to rename ``yocto_colorled`` into ``colorled``. Since the file is inside the ``yocto_api/`` directory there is no name conflict.

From a Python script file just do:
```
from yocto_api.colorled import *
```

**Comment by yoctopuce** [comment]
Hi,

Few years ago, when we started this library we had no experience in python and we chose this unconventional file structure, because it is most similar to C++ and PHP language and make our libraries homogeneous 

Your modifications are interesting, but we will not apply these changes. Here is why:

- We have too many examples and customers that are using this library. These changes will break existing code and make many users unhappy.
- We already have made similar changes for the PyPI package of this library. 
  So if you prefer to use a python package you can use the one that is on PyPI
  See: https://pypi.python.org/pypi/yoctopuce. 

I hope that you understand our position.

**Comment by LudovicRousseau** [comment]
I did not know the PyPI package. I suggest to mention it in http://www.yoctopuce.com/FR/libraries.php or at least in the ``README.md`` file of this project.

**Comment by yoctopuce** [comment]
I've updated the README.md.

**Pull request closed without merging**
